### ISSUE TITLE
Change Json string format in java before deserializing it to POJO using GSON

### ISSUE THREAD

**Issue by ruisousa10** [google/gson#711]
I have the following Json string:

{
  "Status": "true",
  "Result": {
    "rows": {
      "row": {
        "status": true,
        "subareas": [
          {
            "nome": "Associacao Utente",
            "id": 9,
            "grafs": {
              "rows": {
                "row": {
                  "id": 6,
                  "nome": "Associacao Utente",
                  "tipo": "PIE",
                  "serv": "MV_AS_UTENTE_POR_NEGOCIO",
                  "periodo": "ANO"
                }
              }
            }
          },
          {
            "nome": "Chaves",
            "id": 60,
            "grafs": {
              "rows": [
                {
                  "id": 35,
                  "nome": "Chaves Criados por ano",
                  "tipo": "LINHA",
                  "serv": "MV_ASSOC_TOTAL_CHAVES",
                  "periodo": "ANO"
                },
                {
                  "id": 592,
                  "nome": "Chaves Associado Ao User Portal",
                  "tipo": "BAR",
                  "serv": "MV_ASSOC_USER_CHAVES",
                  "periodo": "TODOS"
                },
                {
                  "id": 593,
                  "nome": "Chaves Associado Ao Negocios",
                  "tipo": "BAR",
                  "serv": "MV_ASSOC_CHAVES",
                  "periodo": "TODOS"
                }
              ]
            }
          }
        ]
      }
    }
  }
}

I'm suppose to deserialize it using GSON but i have an issue. If you look at the first "subarea" you will notice it as a "grafs" key like this:
"grafs": {
              "rows": {
                "row": {
and the second "suberarea" have "grafs" this way:
 "grafs": {
              "rows": [
i.e one is an object and the second an array. The is valid but the data is inconsistent, so i need to change this string programmaticaly, without touching the raw string since it comes from a server.
How can i change the string before deserialize. I want to make both "grafs" arrays.

thanks for your help!

**Comment by JakeWharton** [comment]
Something like:
```java
public final class ListFromObjectAdapter implements TypeAdapterFactory {
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    if (List.class != type.getRawType()) {
      throw new AssertionError("Adapter can only be set on List type.");
    }
    final TypeAdapter<T> delegateAdapter = gson.getDelegateAdapter(this, type);

    Type collectionType = $Gson$Types.getCollectionElementType(type.getType(), type.getRawType());
    final TypeAdapter<?> elementAdapter = gson.getAdapter(TypeToken.get(collectionType));

    return new TypeAdapter<T>() {
      @Override public void write(JsonWriter out, T value) throws IOException {
        delegateAdapter.write(out, value);
      }

      @Override public T read(JsonReader in) throws IOException {
        if (in.peek() != JsonToken.BEGIN_ARRAY) {
          Object value = elementAdapter.read(in);
          //noinspection unchecked
          return (T) Collections.singletonList(value);
        }
        return delegateAdapter.read(in);
      }
    };
  }

  public static void main(String... args) {
    String jsonCorrect = "{\"things\":[\"hey!\"]}";
    String jsonBroken = "{\"things\":\"hey!\"}";

    Gson gson = new Gson();
    Test testCorrect = gson.fromJson(jsonCorrect, Test.class);
    System.out.println("Correct: " + testCorrect.things);
    Test testBroken = gson.fromJson(jsonBroken, Test.class);
    System.out.println("Broken (but fixed!): " + testBroken.things);
  }

  private static class Test {
    @JsonAdapter(ListFromObjectAdapter.class)
    List<String> things;
  }
}
```
Note: this uses Gson's internal `$Gson$Types` class which is subject to change, deletion, or general breakage at any time!

**Comment by JakeWharton** [comment]
Output is:
```
Correct: [hey!]
Broken (but fixed!): [hey!]
```

**Comment by ruisousa10** [comment]
$Gson$Types and elementAdapter it is throwing the cannot find symbol error.

**Comment by ruisousa10** [comment]
![listfromobject](https://cloud.githubusercontent.com/assets/15041888/10393166/9c4d2b30-6e74-11e5-84ac-4e37e537c75b.JPG)

**Comment by ruisousa10** [comment]
Using @JsonAdapter in my class it's giving me this error.

![listfromobject](https://cloud.githubusercontent.com/assets/15041888/10394480/abc892ac-6e7e-11e5-8184-e4732ada5203.JPG)

**Comment by JakeWharton** [comment]
Are you using Gson 2.4?

**Comment by ruisousa10** [comment]
Yes

**Comment by JakeWharton** [comment]
Then you likely are importing the wrong versions of those classes. Both
should be coming from Gson's package. $Gson$Types comes from the 'internal'
package.

**Comment by ruisousa10** [comment]
@JakeWharton i've imported $Gson$Types and still gives me the error. Should i use Gson 2.4?

**Comment by ruisousa10** [comment]
@JakeWharton it is working with Gson 2.4. The only issue i have now is the following.

![listfromobject](https://cloud.githubusercontent.com/assets/15041888/10397320/30c39f10-6e8e-11e5-9ee5-d99422d5b68a.JPG)

I think i'm on the right way, almost there, thanks to you.
