### ISSUE TITLE
NoSuchMethodError when serializing Object with boolean members

### ISSUE THREAD

**Issue by dflorey** [google/gson#2296]
# Gson version
2.10.1

# Description
After upgrading from gson 2.2.4 to 2.10.1 I'm running into this exception:
[INFO] GCLOUD: Caused by: java.lang.NoSuchMethodError: 'com.google.gson.stream.JsonWriter com.google.gson.stream.JsonWriter.value(java.lang.Boolean)'       
[1] [INFO] GCLOUD:      at com.google.gson.internal.bind.TypeAdapters$3.write(TypeAdapters.java:150)
[1] [INFO] GCLOUD:      at com.google.gson.internal.bind.TypeAdapters$3.write(TypeAdapters.java:135)
[1] [INFO] GCLOUD:      at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
[1] [INFO] GCLOUD:      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
[1] [INFO] GCLOUD:      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:368)
[INFO] GCLOUD:  at com.google.gson.Gson.toJson(Gson.java:842)
[1] [INFO] GCLOUD:      at com.google.gson.Gson.toJson(Gson.java:812)
[1] [INFO] GCLOUD:      at com.google.gson.Gson.toJson(Gson.java:759)
[1] [INFO] GCLOUD:      at com.floreysoft.ultradox.server.entity.ItemEntity.setItem(ItemEntity.java:75)

I can see that there is a method in JsonWriter dealing with boolean, but it seems not to be able to dispatch the java.lang.Boolean to that method.
It used to work just fine with the old version, but it looks like all the reflection stuff has been added / changed.
Help!

**Comment by dflorey** [comment]
I just made some more tests and it still works with gson 2.6.2.

**Comment by eamonnmcmanus** [comment]
Are you using ProGuard or some other app-shrinking technology? This looks as if something is deleting a method because it wrongly thinks it is unused. Another possibility is that you have more than one version of Gson on your classpath. I see that 2.6.2 [did not have](https://github.com/google/gson/blob/fe62b04148a0fe09cb38dcb667a5053b89e6c76d/gson/src/main/java/com/google/gson/stream/JsonWriter.java#L464) a method `JsonWriter.value(Boolean)`. You could try something like this:

```
System.out.println(
    JsonWriter.class.getProtectionDomain().getCodeSource().getLocation());
```

which is the ridiculously roundabout way of finding out where a class is coming from.

**Comment by dflorey** [comment]
Thanks for getting back to me! I'll try tomorrow when I'm back coding (Germany).
I am not using an app-shrinking toolchain and I double-checked today that there is only one gson version deployed, as this also was my first guess (not sure if appengine itself comes with some gson version that screws things up though).
I'll give your location-detector a try :)

**Comment by dflorey** [comment]
Thanks so much for the tip, it was gold. The old JsonWriter came from a different jar with the same classname.
Now everything works as expected. The issue can be closed.
