### ISSUE TITLE
AssertionError(String, NoSuchFieldException) not available against my java compiler?

### ISSUE THREAD

**Issue by xete** [google/gson#799]
I was to introduce gson to my project but it failed without the implement of the constructor `AssertionError(String,NoSuchFieldException)`

> com/google/gson/internal/bind/TypeAdapters.java:812: error: no suitable constructor found for AssertionError(String,NoSuchFieldException)

`javac -version` outputs `javac 1.7.0_91`
But as the [document](https://docs.oracle.com/javase/7/docs/api/java/lang/AssertionError.html) says,
it's available sine 1.4.
Though with some tricks I can workaround it, I wonder eagerly why this happen.

**Comment by bes1002t** [comment]
If I remember rightly, Gson just works with no-args constructors.

**Comment by Marcono1234** [comment]
Might have been caused by #738 which by accident used a constructor introduced in Java 7, even though back then Java 6 was the target version of this project. Either way, that was fixed by #857 and later refactored, so this should not be an issue anymore.
