### ISSUE TITLE
NoSuchMethodError on Android

### ISSUE THREAD

**Issue by PromanSEW** [google/gson#1941]
After update 2.8.6 to 2.8.7 I got exception:
```
Caused by java.lang.AssertionError: java.lang.NoSuchFieldException: error
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at retrofit2.converter.gson.GsonConverterFactory.responseBodyConverter(GsonConverterFactory.java:64)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
       at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:113)
       at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:82)
       at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:37)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
      ...
```

**Comment by eamonnmcmanus** [comment]
This should be fixed by #1495, which is included in the just-released 2.8.8.
